#!/bin/sh
FILE="/tmp/speech"
if [ -e $FILE ];then
    rm $FILE
fi
mkfifo $FILE
chmod 777 $FILE

if [ "$(uname)" == 'Darwin' ]; then
  OS='Mac'
elif [ "$(expr substr $(uname -s) 1 5)" == 'Linux' ]; then
  OS='Linux'
elif [ "$(expr substr $(uname -s) 1 10)" == 'MINGW32_NT' ]; then                                                                                           
  OS='Cygwin'
else
  echo "Your platform ($(uname -a)) is not supported."
  exit 1
fi

${HOME}/bin/sp &
if [ "${OS}" == 'Mac' ]; then
    script $FILE
else 
    script -f $FILE
fi
